#+title: Research
#+author: Mark Hartigan
#+email: mark.hartigan@protonmail.com
#+options: toc:nil num:nil
#+options: html-link-use-abs-url:nil html-postamble:t
#+options: html-preamble:t html-scripts:t html-style:nil
#+options: html5-fancy:nil tex:t
#+description:
#+keywords:
#+html_link_home: index.html
#+html_link_up:
#+html_mathjax:
#+html_head: <link rel="preconnect" href="https://fonts.gstatic.com">
#+html_head: <link href="https://fonts.googleapis.com/css2?family=Ubuntu+Mono&display=swap" rel="stylesheet">
#+html_head: <link rel="stylesheet" type="text/css" href="css/stylesheet.css" />
#+html_head: <link rel="icon" type="image/png" href="ref/favicon.png" />
#+html_head: <script data-goatcounter="https://mchartigan.goatcounter.com/count" async src="//gc.zgo.at/count.js"></script>
#+subtitle:
#+latex_header:

* Vestigo Aerospace LLC: [[https://www.sbir.gov/node/1881753][Aerodynamically Stable DragSails for Spacecraft Deorbit]]

I worked for this company while at Purdue University during the summer of 2021. I primarily programmed the microcontroller to control drag sail deployment, timing, etc. ([[https://www.ti.com/product/MSP430FR5969][MSP430FR5969]] if you're curious). This is a device the end user can interface with over I2C, SPI, or UART to control various parameters pertinent to the drag sail. I concluded my summer by presenting my work in a Code Design Review to the company and an expert on the subject matter.

* Purdue University: [[https://engineering.purdue.edu/CubeSat/missions/femta][FEMTA Suborbital Flight Experiment]]

I was project manager for spring 2021 and was an undergraduate researcher here since Fall 2019

Our [[https://github.com/FEMTA-Suborbital-Experiment][Github]] is publicly viewable

Conference Presentations:
+ *Hartigan, M.*, Degener, M., (2021). "Using Plasma Spectroscopy to Measure Thrust of Micropropulsion Systems". In /Spring 2021 AAE Research Symposium Series/. West Lafayette, IN.
+ Lumpp, B., Ayhan, D., Deperna, J., *Hartigan, M.*, Hawn, E., Johnson, A., Kinsella, J., Kracke-Bock, C., Patel, J., (2020). "Zero-Gravity Testing of a FEMTA Thruster Through Plasma Spectroscopy". In /Fall 2020 Purdue Undergraduate Research Conference/. West Lafayette, IN.
+ Lumpp, B., Chow, J., Deperna, J., *Hartigan, M.*, Johnson, A., Kinsella, J., (2020). "Developing a Numerical Model of the FEMTA Propellant Management Experiment". In /Fall 2020 Purdue Undergraduate Research Conference/. West Lafayette, IN.
+ Lumpp, B., Cavanaugh, B., Degener, M., Deperna, J., Govindhan, A., *Hartigan, M.*, Menon, A., Park, J., Patel, J., (2020). "Optimizing, Testing, and Manufacturing the FEMTA Propellant Management System Design". In /Fall 2020 Purdue Undergraduate Research Conference/. West Lafayette, IN.
+ Chow, J., Czech, C., Degener, M., Franks, .N, Govindhan, A., *Hartigan, M.*, Kiddy, S., Kracke-Bock, C., Lumpp, A., Lumpp, B., Menon, A., Patel, R., Shahin, T., Soberg, J., Yu, Y., (2020). "Suborbital Testing of a Small Satellite Propulsion System". In /Spring 2020 Purdue Undergraduate Research Conference/. West Lafayette, IN.

